### ISSUE TITLE
Support for WebDriver Tests

### ISSUE THREAD

**Issue by rhmms** [provocon/coremedia-build-docker#2]
It seems the image is missing webdriver integration. Chromium is not installed and working. PhantomJS is installed (deprecated by CoreMedia as of CM10), however it segfaults: 

```
# phantomjs
phantomjs: Relink `/usr/lib/libpng16.so.16' with `/usr/glibc-compat/lib/libm.so.6' for IFUNC symbol `floor'
Segmentation fault
```

It seems phantomjs needs to be built differently on alpine: https://henry.wang/2018/03/13/phantomjs-for-npm-on-alpine.html
 
When installing chromium and chromium-webdriver in the image, the coremedia 10 blueprint tests still fail with: 

```
Caused by: org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
```

It seems that is another issue.

**Comment by blackappsolutions** [comment]
First of all: Thank you so much @rhmms for bringing this up. If you have found a solution so far, please share.

After investigating 2 hours in this issue and none of the fixes I found so far really worked, i would recommend dropping phantomjs-support in THIS build container. 

As CoreMedia says in their docs, you need this only for testing your studio extensions (correct me if I am wrong) AND because phantomjs is so old and deprecated I expect a drop of this dependency soon.

https://documentation.coremedia.com/cmcc-10/artifacts/1907/webhelp/coremedia-en/content/developing_studio.html#developing_studio_joo_unit
-------------snipp-------------
* Joo Unit Testing

The jangaroo-maven-plugin supports unit testing of ActionScript classes inside the Studio modules. Please refer to Jangaroo Tools Wiki, chapter "Unit Testing". To run the tests, you need to meet one of the following preconditions:

    Google Chrome is installed

    Another supported browser (firefox, edge, iexplorer) is installed and is specified by property -DjooUnitWebDriverBrowser=...

    PhantomJS version 2.1.1 is installed and available on your PATH or its location is specified by property phantomjs.bin. PhantomJS is discontinued, so using it is discouraged. 

If none of the preconditions are met, you can still build by skipping Jangaroo unit tests by activating Maven profile skip-joo-unit-tests.

-------------snipp-------------

**Comment by rhmms** [comment]
I was able to fix this (after some hours of debugging webdriver and headless chrome). 
I installed chrome and chromedriver in the image:
```
apk add git chromium-chromedriver chromium python mesa-gles
```
Then I was able to run maven with these settings:
```
mvn install -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dwebdriver.chrome.verboseLogging=true -DjooUnitWebDriverBrowserArguments=--no-sandbox,--disable-dev-shm-usage
```
With this I get a green build for coremedia 10 incuding the selenium tests using chrome headless in the container. I can even build the docker images from within the container if I run it with the docker socket mounted:
```
..  -v /var/run/docker.sock:/var/run/docker.sock ....
```
P.s. python was missing for some nodejs stuff.

One interesting note. Actually jangaroo tools should have a fix for this (https://github.com/CoreMedia/jangaroo-tools/pull/63), however it is merged to master-4 branch and I am not sure if this made it into a release. Strange branching strategy I suppose.

**Comment by mgoellnitz** [comment]
A, thanks, great we'll check this. We had a hard time with a nice chain of failures trying other approaches with force use of phantomjs, original chrome, and the chromedriver which the workspace insists to use.

**Comment by mgoellnitz** [comment]
@blackappsolutions worked along another path and we just pushed his results as "latest", which are able to run tests for us. Can you confirm this @rhmms ?

**Comment by mgoellnitz** [comment]
Fixed, and examples tuned.

**Comment by rhmms** [comment]
Worked for me.
